#!/bin/sh
# $Source$
# $State$
#
# Script to build a distribution package.

set -e
PACKAGE=wordgrinder
	
if [ "$1" = "" ]; then
	echo "Please specify a version number!"
	exit 1
fi

if [ -d ../$PACKAGE-$1 ]; then
	echo "I think you've already generated version $1."
	exit 1
fi

mkdir ../$PACKAGE-$1
cp -a --parents \
	./COPYING \
	./Makefile \
	./README.Unix \
	./README.Windows.txt \
	./README.wg \
	./extras/icon-broken.xcf.gz \
	./extras/icon-sized.xcf.gz \
	./extras/icon-unbroken.xcf.gz \
	./extras/windows-installer.nsi \
	./src/c/arch/unix/cursesw/dpy.c \
	./src/c/arch/win32/console/dpy.c \
	./src/c/arch/win32/gdi/dpy.c \
	./src/c/arch/win32/gdi/gdi.h \
	./src/c/arch/win32/gdi/glyphcache.c \
	./src/c/arch/win32/gdi/realmain.c \
	./src/c/arch/win32/gdi/uthash.h \
	./src/c/arch/win32/gdi/utlist.h \
	./src/c/arch/win32/icon.ico \
	./src/c/arch/win32/wordgrinder.rc \
	./src/c/emu/wcwidth.c \
	./src/c/globals.h \
	./src/c/lfs/lfs.c \
	./src/c/lfs/lfs.h \
	./src/c/lfs/COPYING \
	./src/c/lua.c \
	./src/c/main.c \
	./src/c/minizip/COPYING \
	./src/c/minizip/README \
	./src/c/minizip/crypt.h \
	./src/c/minizip/ioapi.c \
	./src/c/minizip/ioapi.h \
	./src/c/minizip/unzip.c \
	./src/c/minizip/unzip.h \
	./src/c/minizip/zip.c \
	./src/c/minizip/zip.h \
	./src/c/screen.c \
	./src/c/utils.c \
	./src/c/word.c \
	./src/c/zip.c \
	./src/lua/_prologue.lua \
	./src/lua/addons/autosave.lua \
	./src/lua/addons/docsetman.lua \
	./src/lua/addons/goto.lua \
	./src/lua/addons/scrapbook.lua \
	./src/lua/browser.lua \
	./src/lua/cli.lua \
	./src/lua/document.lua \
	./src/lua/events.lua \
	./src/lua/export/html.lua \
	./src/lua/export/latex.lua \
	./src/lua/export/opendocument.lua \
	./src/lua/export/text.lua \
	./src/lua/export/troff.lua \
	./src/lua/export.lua \
	./src/lua/fileio.lua \
	./src/lua/forms.lua \
	./src/lua/html.lua \
	./src/lua/import/html.lua \
	./src/lua/import/opendocument.lua \
	./src/lua/import/text.lua \
	./src/lua/import.lua \
	./src/lua/main.lua \
	./src/lua/margin.lua \
	./src/lua/menu.lua \
	./src/lua/navigate.lua \
	./src/lua/redraw.lua \
	./src/lua/ui.lua \
	./src/lua/utils.lua \
	./src/lua/xml.lua \
	./testdocs/README-v0.1.wg \
	./testdocs/README-v0.2.wg \
	./testdocs/README-v0.3.3.wg \
	./tools/multibin2c.lua \
	./wordgrinder.man \
	\
	../$PACKAGE-$1

(cd .. && tar cvf $PACKAGE-$1.tar.bz2 --bzip2 $PACKAGE-$1)

echo ""
echo "Done --- but did you remember to update the version number in the README and the makefile?"
