--!strict
loadfile("tests/testsuite.lua")()

local data = [[
This is paragraph 1.
This is 2.

This is 4 (3 was blank).
]]

local document = Cmd.ImportTextString(data)

local expected = [[
%% This document automatically generated by WordGrinder @@@.
\documentclass{article}
\usepackage{xunicode, setspace, xltxtra}
\sloppy
\onehalfspacing
\begin{document}
\title{imported}
\author{(no author)}
\maketitle
This is paragraph 1.

This is 2.

\paragraph{}

This is 4 (3 was blank).

\end{document}
]]
expected = expected:gsub("@@@", VERSION)

DocumentSet:addDocument(document, "imported")
DocumentSet:setCurrent("imported")
local output = Cmd.ExportToLatexString()
AssertEquals(expected, output)


document = Cmd.ImportTextString(9)
document = Cmd.ImportTextString("no trailing newline")
DocumentSet:addDocument(document, "imported")
DocumentSet:setCurrent("imported")
AssertTableEquals({"no", "trailing", "newline"}, Document[1])


